todosData = [
  {
    id: 1,
    title: "Buy groceries for the week",
    oldTitle: "",
    description: "Milk, eggs, bread, fruits, and vegetables",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-15",
    priority: "medium",
    category: "shopping",
    edit: false,
    editDescription: false,
  },
  {
    id: 2,
    title: "Finish React project",
    oldTitle: "",
    description: "Complete the todo app with all features",
    oldDescription: "",
    completed: true,
    dueDate: "2024-01-10",
    priority: "high",
    category: "work",
    edit: false,
    editDescription: false,
  },
  {
    id: 3,
    title: "Call mom",
    oldTitle: "",
    description: "Check how she's doing and plan weekend visit",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-12",
    priority: "medium",
    category: "personal",
    edit: false,
    editDescription: false,
  },
  {
    id: 4,
    title: "Gym workout",
    oldTitle: "",
    description: "Chest and triceps day - 45 minutes",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-11",
    priority: "low",
    category: "health",
    edit: false,
    editDescription: false,
  },
  {
    id: 5,
    title: "Read book",
    oldTitle: "",
    description: "Atomic Habits - Chapter 5",
    oldDescription: "",
    completed: true,
    dueDate: "2024-01-08",
    priority: "low",
    category: "personal",
    edit: false,
    editDescription: false,
  },
  {
    id: 6,
    title: "Prepare meeting presentation",
    oldTitle: "",
    description: "Slides for quarterly review meeting",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-14",
    priority: "high",
    category: "work",
    edit: false,
    editDescription: false,
  },
  {
    id: 7,
    title: "Pay electricity bill",
    oldTitle: "",
    description: "Due by end of the month",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-31",
    priority: "medium",
    category: "finance",
    edit: false,
    editDescription: false,
  },
  {
    id: 8,
    title: "Clean the apartment",
    oldTitle: "",
    description: "Vacuum, dust, and organize living room",
    oldDescription: "",
    completed: true,
    dueDate: "2024-01-07",
    priority: "medium",
    category: "home",
    edit: false,
    editDescription: false,
  },
  {
    id: 9,
    title: "Learn new JavaScript framework",
    oldTitle: "",
    description: "Spend 1 hour learning Vue.js basics",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-13",
    priority: "high",
    category: "learning",
    edit: false,
    editDescription: false,
  },
  {
    id: 10,
    title: "Plan weekend trip",
    oldTitle: "",
    description: "Research hotels and activities for mountain getaway",
    oldDescription: "",
    completed: false,
    dueDate: "2024-01-16",
    priority: "low",
    category: "travel",
    edit: false,
    editDescription: false,
  },
];
// todosData = [];
